<?php

namespace gamboamartin\facturacion\models;

use gamboamartin\comercial\models\com_sucursal;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class fc_factura extends _transacciones_fc
{

    public function __construct(PDO $link, bool $valida_atributos_criticos = true)
    {
        $tabla = 'fc_factura';

        $fc_factura_uuid = "IFNULL($tabla.folio_fiscal,'SIN UUID')";

        $columnas_extra['fc_factura_uuid'] = $fc_factura_uuid;

        parent::__construct(link: $link, tabla: $tabla, columnas_extra: $columnas_extra,
            valida_atributos_criticos: $valida_atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;

        $this->etiqueta = 'Factura';
        $this->key_fc_id = 'fc_factura_id';

    }

    public function alta_bd(): array|stdClass
    {
        $this->modelo_email = new fc_email(link: $this->link);
        $this->modelo_etapa = new fc_factura_etapa(link: $this->link);

        $this->registro['aplica_saldo'] = 'inactivo';

        $r_alta_bd = parent::alta_bd(); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar',data:  $r_alta_bd);
        }

        $regenera = (new _saldos_fc())->regenera_saldos(fc_factura_id: $r_alta_bd->registro_id,link: $this->link);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al regenera',data:  $regenera);
        }

        $fc_factura_id = $r_alta_bd->registro_id;

        $rs = $this->actualiza_recalcula_comison_cliente(fc_factura_id: $fc_factura_id);
        if(errores::$error){
            return $this->error->error(
                mensaje: 'Error al actualizar y calcular comision en la factura',
                data:  $rs
            );
        }


        return $r_alta_bd;
    }

    public function elimina_bd(int $id): array|stdClass
    {

        $this->modelo_etapa = new fc_factura_etapa(link: $this->link);
        $this->modelo_partida = new fc_partida(link: $this->link);
        $this->modelo_documento = new fc_factura_documento(link: $this->link);
        $this->modelo_email = new fc_email(link: $this->link);
        $this->modelo_sello = new fc_cfdi_sellado(link: $this->link);
        $this->modelo_relacionada = new fc_factura_relacionada(link: $this->link);
        $this->modelo_notificacion = new fc_notificacion(link: $this->link);
        $this->modelo_relacion = new fc_relacion(link: $this->link);

        $filtro['fc_factura.id'] = $id;
        $del = (new fc_factura_automatica(link: $this->link))->elimina_con_filtro_and(filtro:$filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al eliminar',data:  $del);
        }

        $result = (new fc_layout_factura(link: $this->link))->elimina_relacion_con_factura_id(fc_factura_id: $id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al eliminar relacion layout',data:  $result);
        }

        $r_elimina_bd = parent::elimina_bd(id: $id); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al eliminar',data:  $r_elimina_bd);
        }
        return $r_elimina_bd;
    }


    public function modifica_bd(array $registro, int $id, bool $reactiva = false,
                                bool $verifica_permite_transaccion = true): array|stdClass
    {
        $this->modelo_etapa = new fc_factura_etapa(link: $this->link);

        $r_modifica_bd = parent::modifica_bd(registro: $registro,id:  $id,reactiva:  $reactiva,
            verifica_permite_transaccion: $verifica_permite_transaccion); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al modificar', data: $r_modifica_bd);
        }
        return $r_modifica_bd;
    }

    public function valida_cep(string $fecha, string $clave_rastreo, string $insitucion_emisora, string $insitucion_receptora,
                               string $cuenta, float $monto, string $receptor_participante): array
    {
        $respuesta = (new _transferencia())->validar(
            fecha: $fecha,
            clave_rastreo: $clave_rastreo,
            insitucion_emisora: $insitucion_emisora,
            insitucion_receptora: $insitucion_receptora,
            cuenta: $cuenta,
            monto: $monto,
            receptor_participante: $receptor_participante
        );
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar CEP',data:  $respuesta);
        }

        return $respuesta;
    }

    public function recalcula_porcentaje_comision_cliente(int $fc_factura_id)
    {
        $fc_factura_data = $this->obtener_datos_factura(fc_factura_id: $fc_factura_id);
        if (errores::$error) {
            return $this->error->error(
                mensaje: 'Error al obtener fc_factura_data',
                data:  $fc_factura_data
            );
        }

        $sub_total_factura = $fc_factura_data['fc_factura_sub_total'];
        $porcentaje_comision_cliente = $fc_factura_data['fc_factura_porcentaje_comision_cliente'];

        $valor_base = $sub_total_factura / (1 + ($porcentaje_comision_cliente / 100));
        $valor_comision = round($sub_total_factura - $valor_base, 2);

        $consulta = "UPDATE fc_factura SET ";
        $consulta .= " fc_factura.comision_cliente = {$valor_comision}";
        $consulta .= " WHERE fc_factura.id = {$fc_factura_id}";
        $rs = $this->ejecuta_sql($consulta);
        if(errores::$error){
            return (new errores())->error('Error al modificar la comision de fc_layout_nom ', $rs);
        }

        return [];
    }

    public function actualiza_porcentaje_comision(int $fc_factura_id)
    {
        $fc_factura_data = $this->obtener_datos_factura(fc_factura_id: $fc_factura_id);
        if (errores::$error) {
            return $this->error->error(
                mensaje: 'Error al obtener fc_factura_data',
                data:  $fc_factura_data
            );
        }

        $nuevo_porcentaje_comision = $fc_factura_data['com_cliente_porcentaje_comision'];

        $consulta = "UPDATE fc_factura SET ";
        $consulta .= " fc_factura.porcentaje_comision_cliente = {$nuevo_porcentaje_comision}";
        $consulta .= " WHERE fc_factura.id = {$fc_factura_id}";
        $rs = $this->ejecuta_sql($consulta);
        if(errores::$error){
            return (new errores())->error('Error al modificar la comision de fc_layout_nom ', $rs);
        }

        return $nuevo_porcentaje_comision;

    }

    private function obtener_datos_factura(int $fc_factura_id)
    {

        $this->registro_id = $fc_factura_id;
        $rs = $this->obten_data();
        if (errores::$error) {
            return $this->error->error(
                mensaje: 'Error al obten_data de fc_factura',
                data:  $rs
            );
        }

        return $rs;
    }

    private function actualiza_recalcula_comison_cliente(int $fc_factura_id)
    {
        $fc_factura_data = $this->obtener_datos_factura(fc_factura_id: $fc_factura_id);
        if (errores::$error) {
            return $this->error->error(
                mensaje: 'Error al obtener fc_factura_data',
                data:  $fc_factura_data
            );
        }

        $sub_total_factura = $fc_factura_data['fc_factura_sub_total'];
        $nuevo_porcentaje_comision = $fc_factura_data['com_cliente_porcentaje_comision'];


        $valor_base = $sub_total_factura / (1 + ($nuevo_porcentaje_comision / 100));
        $valor_comision = round($sub_total_factura - $valor_base, 2);

        $consulta = "UPDATE fc_factura SET ";
        $consulta .= " fc_factura.comision_cliente = {$valor_comision} ,";
        $consulta .= " fc_factura.porcentaje_comision_cliente = {$nuevo_porcentaje_comision}";
        $consulta .= " WHERE fc_factura.id = {$fc_factura_id}";
        $rs = $this->ejecuta_sql($consulta);
        if(errores::$error){
            return (new errores())->error('Error al actualiza_recalcula_comison_cliente', $rs);
        }

        return [];
    }

    public function asigna_bd(int $id): array
    {

        $consulta = "UPDATE {$this->tabla} SET {$this->tabla}.asignado_fc_layout = 'activo' WHERE {$this->tabla}.id = {$id}";
        $rs = $this->ejecuta_sql($consulta);
        if(errores::$error){
            return (new errores())->error("Error al asignar {$this->tabla}", $rs);
        }

        return [];
    }

    public function desasigna_bd(int $id): array
    {

        $consulta = "UPDATE {$this->tabla} SET {$this->tabla}.asignado_fc_layout = 'inactivo' WHERE {$this->tabla}.id = {$id}";
        $rs = $this->ejecuta_sql($consulta);
        if(errores::$error){
            return (new errores())->error("Error al desasignar {$this->tabla}", $rs);
        }

        return [];
    }

    public function obtener_facturas_con_sucursal(int $com_sucursal_id): array
    {
        $com_sucursal_modelo = new com_sucursal($this->link);
        $com_sucursal_modelo->registro_id = $com_sucursal_id;
        $rs1 = $com_sucursal_modelo->obten_data(columnas: ['com_cliente_id']);
        if (errores::$error) {
            return $this->error->error(
                mensaje: 'Error al obtener data de sucursal',
                data:  $rs1
            );
        }

        $com_cliente_id = $rs1['com_cliente_id'];

        $filtro = [
            'com_cliente.id' => $com_cliente_id,
            'fc_factura.etapa' => 'TIMBRADO',
            'fc_factura.asignado_fc_layout' => 'inactivo',
        ];

        $columnas = [
            'fc_factura_folio','fc_factura_total','com_cliente_razon_social',
            'fc_factura_fecha','fc_factura_id'
        ];

        $rs2 = $this->filtro_and(columnas: $columnas, filtro: $filtro);
        if (errores::$error) {
            return $this->error->error(
                mensaje: 'Error al obtener facturas',
                data:  $rs2
            );
        }

        return $rs2->registros;

    }


}