<?php
namespace gamboamartin\facturacion\models;
use base\orm\modelo;
use gamboamartin\documento\models\doc_documento;
use gamboamartin\errores\errores;
use PDO;
use stdClass;


class fc_layout_nom extends modelo{
    public function __construct(PDO $link){
        $tabla = 'fc_layout_nom';
        $columnas = array($tabla=>false,'doc_documento'=>$tabla);

        $campos_view = array();
        $campos_obligatorios = array();
        $no_duplicados = array();


        parent::__construct(link: $link,tabla:  $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, campos_view: $campos_view, no_duplicados: $no_duplicados);

        $this->NAMESPACE = __NAMESPACE__;

        $this->etiqueta = 'Layout Nomina';
    }

    public function alta_bd(): array|stdClass
    {
        $rand_code = mt_rand(10,99);
        if(isset($this->registro['id'])){
            $existe = $this->existe_by_id($this->registro['id']);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al ver si existe', data: $existe);
            }
            if($existe){
                return new stdClass();
            }
            $rand_code = $rand_code.$this->registro['id'];

        }

        $file = $_FILES['documento'];

        $doc_documento_modelo = new doc_documento(link: $this->link);
        $doc_documento_ins['doc_tipo_documento_id'] = 11;
        $doc_documento_ins['name_out'] = $_FILES['documento']['name'];


        $doc_documento_alta = $doc_documento_modelo->alta_documento(registro:$doc_documento_ins,file: $file);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar doc', data: $doc_documento_alta);
        }

        $doc_documento_id = $doc_documento_alta->registro_id;

        $this->registro['codigo'] = 'LDN.'.date('YmdHis').'.'.mt_rand(10,99).$rand_code;
        $this->registro['codigo_bis'] = 'LDN.'.date('YmdHis').'.'.mt_rand(10,99).$rand_code;
        $this->registro['status'] = 'activo';
        $this->registro['descripcion'] = $this->registro['descripcion'].' '.$doc_documento_ins['name_out'];
        $this->registro['doc_documento_id'] = $doc_documento_id;
        $this->registro['fecha_emision'] = $_POST['fecha_pago'].'T'.date('H:i:s');

        $_POST['fecha_emision'] = $_POST['fecha_pago'].'T'.date('H:i:s');

        $r_alta = parent::alta_bd();
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al dar de alta registro',data: $r_alta);
        }
        return $r_alta;

    }

    public function modifica_bd(array $registro, int $id, bool $reactiva = false): array|stdClass
    {
        $this->link->beginTransaction();
        if (array_key_exists('fecha_emision', $registro)) {
            $fecha_emision = $registro['fecha_emision'];

            $result = $this->modifica_fecha_emision_row_layout($id, $fecha_emision);
            if(errores::$error){
                $this->link->rollBack();
                return $this->error->error(mensaje: 'Error en modifica_fecha_emision_row_layout',data: $result);
            }
        }

        $r_modifica_bd = parent::modifica_bd($registro, $id, $reactiva); // TODO: Change the autogenerated stub
        if(errores::$error){
            $this->link->rollBack();
            return $this->error->error(mensaje: 'Error al modificar el registro',data: $r_modifica_bd);
        }
        $this->link->commit();
        return $r_modifica_bd;
    }

    private function modifica_fecha_emision_row_layout(int $fc_layout_nom_id, string $fecha_emision)
    {
        $fc_row_layout_modelo = new fc_row_layout(link: $this->link);
        $filtro = array();
        $filtro['fc_row_layout.fc_layout_nom_id'] = $fc_layout_nom_id;
        $filtro['fc_row_layout.esta_timbrado'] = 'inactivo';

        $upd_row = array();
        $upd_row['fecha_emision'] = $fecha_emision;

        $result = $fc_row_layout_modelo->filtro_and(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener los registros',data: $result);
        }

        $data = [];

        foreach ($result->registros as $registro) {
            $id = $registro['fc_row_layout_id'];
            $rs_upd = $fc_row_layout_modelo->modifica_bd($upd_row, $id);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al modificar el registro',data: $result);
            }
            $data[] = $rs_upd;
        }

        return $data;
    }

}