<?php
namespace gamboamartin\facturacion\models;
use base\orm\modelo;
use gamboamartin\comercial\models\com_sucursal;
use gamboamartin\documento\models\doc_documento;
use gamboamartin\errores\errores;
use gamboamartin\facturacion\controllers\controlador_com_contacto;
use PDO;
use stdClass;


class fc_layout_nom extends modelo{
    public function __construct(PDO $link){
        $this->campo_asignacion = 'asignado_fc_factura'; //campo necesario para la accion asigna modelo
        $tabla = 'fc_layout_nom';
        $columnas = [
            $tabla=>false, 'doc_documento'=>$tabla, 'com_sucursal'=>$tabla,
            'com_cliente' => 'com_sucursal'
        ];

        $campos_view = array();
        $campos_obligatorios = array();
        $no_duplicados = array();


        parent::__construct(link: $link,tabla:  $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, campos_view: $campos_view, no_duplicados: $no_duplicados);

        $this->NAMESPACE = __NAMESPACE__;

        $this->etiqueta = 'Layout Nomina';
    }

    public function alta_bd(): array|stdClass
    {
        $rand_code = mt_rand(10,99);
        if(isset($this->registro['id'])){
            $existe = $this->existe_by_id($this->registro['id']);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al ver si existe', data: $existe);
            }
            if($existe){
                return new stdClass();
            }
            $rand_code = $rand_code.$this->registro['id'];

        }

        $file = $_FILES['documento'];

        $doc_documento_modelo = new doc_documento(link: $this->link);
        $doc_documento_ins['doc_tipo_documento_id'] = 11;
        $doc_documento_ins['name_out'] = $_FILES['documento']['name'];


        $doc_documento_alta = $doc_documento_modelo->alta_documento(registro:$doc_documento_ins,file: $file);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar doc', data: $doc_documento_alta);
        }

        $porcentaje_comision_cliente = $this->obtener_porcentaje_comision_by_com_sucursal_id(
            com_sucursal_id: $_POST['com_sucursal_id']
        );
        if(errores::$error){
            return $this->error->error(
                mensaje: 'Error al obtener el porcentaje_comision_cliente',
                data: $porcentaje_comision_cliente
            );
        }

        $doc_documento_id = $doc_documento_alta->registro_id;

        $this->registro['codigo'] = 'LDN.'.date('YmdHis').'.'.mt_rand(10,99).$rand_code;
        $this->registro['codigo_bis'] = 'LDN.'.date('YmdHis').'.'.mt_rand(10,99).$rand_code;
        $this->registro['status'] = 'activo';
        $this->registro['descripcion'] = $this->registro['descripcion'].' '.$doc_documento_ins['name_out'];
        $this->registro['doc_documento_id'] = $doc_documento_id;
        $this->registro['fecha_emision'] = $_POST['fecha_pago'].'T'.date('H:i:s');
        $this->registro['porcentaje_comision_cliente'] = $porcentaje_comision_cliente;

        $_POST['fecha_emision'] = $_POST['fecha_pago'].'T'.date('H:i:s');
        $_POST['porcentaje_comision_cliente'] = $porcentaje_comision_cliente;

        $r_alta = parent::alta_bd();
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al dar de alta registro',data: $r_alta);
        }
        return $r_alta;

    }

    public function modifica_bd(array $registro, int $id, bool $reactiva = false): array|stdClass
    {
        $this->link->beginTransaction();
        if (array_key_exists('fecha_emision', $registro)) {
            $fecha_emision = $registro['fecha_emision'];

            $result = $this->modifica_fecha_emision_row_layout($id, $fecha_emision);
            if(errores::$error){
                $this->link->rollBack();
                return $this->error->error(mensaje: 'Error en modifica_fecha_emision_row_layout',data: $result);
            }
        }

        $r_modifica_bd = parent::modifica_bd($registro, $id, $reactiva); // TODO: Change the autogenerated stub
        if(errores::$error){
            $this->link->rollBack();
            return $this->error->error(mensaje: 'Error al modificar el registro',data: $r_modifica_bd);
        }
        $this->link->commit();
        return $r_modifica_bd;
    }

    public function elimina_bd(int $id): array|stdClass
    {
        // 1. Validar que no existan registros timbrados
        $fc_row_layout_modelo = new fc_row_layout(link: $this->link);
        $filtro_timbrados = array();
        $filtro_timbrados['fc_row_layout.fc_layout_nom_id'] = $id;
        $filtro_timbrados['fc_row_layout.esta_timbrado'] = 'activo';

        $result_timbrados = $fc_row_layout_modelo->filtro_and(filtro: $filtro_timbrados);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al verificar registros timbrados',data: $result_timbrados);
        }

        if($result_timbrados->n_registros > 0){
            return $this->error->error(
                mensaje: 'No se puede eliminar el layout porque tiene '.$result_timbrados->n_registros.' recibo(s) timbrado(s). Los documentos timbrados no pueden eliminarse',
                data: array('fc_layout_nom_id' => $id, 'recibos_timbrados' => $result_timbrados->n_registros)
            );
        }

        // 2. Obtener todos los fc_row_layout relacionados (solo no timbrados)
        $filtro = array();
        $filtro['fc_row_layout.fc_layout_nom_id'] = $id;

        $result = $fc_row_layout_modelo->filtro_and(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener fc_row_layout',data: $result);
        }

        // 3. Eliminar cada fc_row_layout y sus hijos (que no esté timbrado)
        foreach ($result->registros as $registro) {
            $fc_row_layout_id = $registro['fc_row_layout_id'];

            // Eliminar el fc_row_layout
            $rs_del = $fc_row_layout_modelo->elimina_bd(id: $fc_row_layout_id);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al eliminar fc_row_layout',data: $rs_del);
            }
        }

        // 4. Eliminar el fc_layout_nom
        $r_elimina_bd = parent::elimina_bd($id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al eliminar fc_layout_nom',data: $r_elimina_bd);
        }

        $rs = (new fc_layout_factura($this->link))->elimina_relacion_con_layout_nom_id(fc_layout_nom_id: $id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al elimina_relacion_con_layout_nom_id',data: $rs);
        }

        return $r_elimina_bd;
    }

    public function cambiar_status_layout(int $registro_id, string $status_layout)
    {
        $r_modifica = $this->modifica_bd(
            registro: ['estado_layout' => $status_layout],
            id: $registro_id,
        );
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar estado_layout',data: $r_modifica);
        }

        return $r_modifica;
    }

    public function desactiva_bd(): array|stdClass
    {
        $r_desactiva = parent::desactiva_bd(); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al desactiva_bd de fc_layout_nom',data: $r_desactiva);
        }

        $rs = (new fc_layout_factura($this->link))
            ->elimina_relacion_con_layout_nom_id(fc_layout_nom_id: $this->registro_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al elimina_relacion_con_layout_nom_id',data: $rs);
        }

        return $r_desactiva;
    }

    private function modifica_fecha_emision_row_layout(int $fc_layout_nom_id, string $fecha_emision)
    {
        $fc_row_layout_modelo = new fc_row_layout(link: $this->link);
        $filtro = array();
        $filtro['fc_row_layout.fc_layout_nom_id'] = $fc_layout_nom_id;
        $filtro['fc_row_layout.esta_timbrado'] = 'inactivo';

        $upd_row = array();
        $upd_row['fecha_emision'] = $fecha_emision;

        $result = $fc_row_layout_modelo->filtro_and(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener los registros',data: $result);
        }

        $data = [];

        foreach ($result->registros as $registro) {
            $id = $registro['fc_row_layout_id'];
            $rs_upd = $fc_row_layout_modelo->modifica_bd($upd_row, $id);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al modificar el registro',data: $result);
            }
            $data[] = $rs_upd;
        }

        return $data;
    }

    public function obten_correos_contactos_cliente(int $fc_layout_nom_id): array
    {
        $this->registro_id = $fc_layout_nom_id;
        $data = $this->obten_data(['com_sucursal_id']);
        if(errores::$error){
            return $this->error->error(
                mensaje: 'Error al obtener datos de fc_layout_nom_id='.$fc_layout_nom_id,
                data: $data
            );
        }

        $com_sucursal_id = $data['com_sucursal_id'];
        if (!$com_sucursal_id) {
            return $this->error->error(
                mensaje: 'Error no existe una sucursal relacionada al fc_layout_nom_id='.$fc_layout_nom_id,
                data: $data
            );
        }

        $com_sucursal_modelo = new com_sucursal($this->link);
        $com_sucursal_modelo->registro_id = $com_sucursal_id;
        $data_com_sucursal = $com_sucursal_modelo->obten_data();
        if(errores::$error){
            return $this->error->error(
                mensaje: 'Error al obtener datos de com_sucursal_id='.$com_sucursal_id,
                data: $data_com_sucursal
            );
        }

        $com_cliente_id = $data_com_sucursal['com_cliente_id'];

        if (!$com_cliente_id) {
            return $this->error->error(
                mensaje: 'Error no existe un cliente relacionada al com_sucursal_id='.$com_sucursal_id,
                data: $data_com_sucursal
            );
        }

        $filtro = [
            'com_contacto.com_cliente_id' => $com_cliente_id,
            'com_contacto.estatus_correo' => controlador_com_contacto::STATUS_VALIDADO,
        ];

        $rs = (new com_contacto($this->link))->filtro_and(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(
                mensaje: 'Error al obtener datos de com_contacto',
                data: $rs
            );
        }

        $correos = [];
        foreach ($rs->registros as $registro) {
            $correos[] = $registro['com_contacto_correo'];
        }

        return $correos;

    }

    public function obtener_porcentaje_comision_by_com_sucursal_id(int $com_sucursal_id)
    {
        $com_sucursal_modelo = new com_sucursal($this->link);
        $com_sucursal_modelo->registro_id = $com_sucursal_id;
        $data_com_sucursal = $com_sucursal_modelo->obten_data(['com_cliente_id']);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener registro com_sucursal',data: $data_com_sucursal);
        }

        $com_cliente_id = $data_com_sucursal['com_cliente_id'];

        $com_cliente_modelo = new com_cliente($this->link);
        $com_cliente_modelo->registro_id = $com_cliente_id;
        $data_com_cliente = $com_cliente_modelo->obten_data(['com_cliente_porcentaje_comision']);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener registro com_cliente',data: $data_com_cliente);
        }

        return (float)$data_com_cliente['com_cliente_porcentaje_comision'];
    }

    public function asigna_bd(int $id): array
    {

        $consulta = "UPDATE {$this->tabla} SET {$this->tabla}.asignado_fc_factura = 'activo' WHERE {$this->tabla}.id = {$id}";
        $rs = $this->ejecuta_sql($consulta);
        if(errores::$error){
            return (new errores())->error("Error al asignar {$this->tabla}", $rs);
        }

        return [];
    }

    public function desasigna_bd(int $id): array
    {

        $consulta = "UPDATE {$this->tabla} SET {$this->tabla}.asignado_fc_factura = 'inactivo' WHERE {$this->tabla}.id = {$id}";
        $rs = $this->ejecuta_sql($consulta);
        if(errores::$error){
            return (new errores())->error("Error al desasignar {$this->tabla}", $rs);
        }

        return [];
    }

}