<?php

namespace gamboamartin\facturacion\models;

use base\orm\_modelo_parent;
use gamboamartin\comercial\models\com_tipo_cambio;
use gamboamartin\errores\errores;
use PDO;
use stdClass;


class fc_pago_pago extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'fc_pago_pago';
        $columnas = array($tabla=>false,'fc_pago'=>$tabla,'com_tipo_cambio'=>$tabla,'cat_sat_forma_pago'=>$tabla,
            'cat_sat_moneda'=>'com_tipo_cambio','fc_complemento_pago'=>'fc_pago');
        $campos_obligatorios = array();


        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Pago pago';
    }

    public function alta_bd(array $keys_integra_ds = array('descripcion')): array|stdClass
    {


        $registro = $this->init_alta($this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al integrar datos',data:  $registro);
        }
        $this->registro = $registro;


        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar',data:  $r_alta_bd);
        }

        $regenera_totales = $this->regenera_totales(fc_pago_id: $this->registro['fc_pago_id']);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener totales',data:  $regenera_totales);
        }


        return $r_alta_bd;
    }

    private function codigo(array $registro): array
    {
        if(!isset($registro['codigo'])){

            $codigo = $registro['fc_pago_id'];
            $codigo .= $registro['fecha_pago'];
            $codigo .= $registro['cat_sat_forma_pago_id'];
            $codigo .= $registro['cat_sat_moneda_id'];
            $codigo .= $registro['com_tipo_cambio_id'];
            $codigo .= $registro['monto'];
            $codigo .= mt_rand(1000,9999);
            $registro['codigo'] = $codigo;
        }
        return $registro;
    }

    /**
     * Integra la moneda en caso de qe no exista basada en el tipo de cambio
     * @param array $registro Registro en proceso
     * @return array
     */
    private function com_tipo_cambio(array $registro): array
    {

        $com_tipo_cambio = (new com_tipo_cambio(link: $this->link))->registro(
            registro_id: $registro['com_tipo_cambio_id']);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener tipo cambio',data:  $com_tipo_cambio);
        }

        if(!isset($registro['cat_sat_moneda_id'])){
            $registro['cat_sat_moneda_id'] = $com_tipo_cambio['cat_sat_moneda_id'];
        }
        return $registro;
    }

    private function descripcion(array $registro): array
    {
        if(!isset($registro['descripcion'])){
            $descripcion = $registro['codigo'];
            $registro['descripcion'] = $descripcion;
        }
        return $registro;

    }

    public function elimina_bd(int $id): array|stdClass
    {

        $registro_previo = $this->registro(registro_id: $id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener registro_previo',data:  $registro_previo);
        }

        $filtro['fc_pago_pago.id'] = $id;
        $del_fc_docto_relacionado = (new fc_docto_relacionado(link: $this->link))->elimina_con_filtro_and(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al eliminar del_fc_docto_relacionado',data:  $del_fc_docto_relacionado);
        }
        $del_fc_impuesto_p = (new fc_impuesto_p(link: $this->link))->elimina_con_filtro_and(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al eliminar del_fc_impuesto_p',data:  $del_fc_impuesto_p);
        }


        $r_elimina = parent::elimina_bd($id); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al eliminar pago',data:  $r_elimina);
        }

        $regenera_totales = $this->regenera_totales(fc_pago_id: $registro_previo['fc_pago_id']);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener totales',data:  $regenera_totales);
        }

        return $r_elimina;

    }

    /**
     * Obtiene los totales de un pago
     * @param int $fc_pago_id Pago a verificar
     * @return array
     * @version 10.11.0
     *
     */
    private function fc_pago_totales(int $fc_pago_id): array
    {
        if($fc_pago_id <= 0){
            return $this->error->error(mensaje: 'Error fc_pago_id debe ser mayor a 0',data:  $fc_pago_id);
        }
        $filtro['fc_pago_id'] = $fc_pago_id;
        $r_fc_pago_total = (new fc_pago_total(link: $this->link))->filtro_and(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener totales',data:  $r_fc_pago_total);
        }

        return $r_fc_pago_total->registros;
    }

    private function init_alta(array $registro){
        $registro = $this->com_tipo_cambio(registro: $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al integrar tipo cambio',data:  $registro);
        }

        $registro = $this->codigo(registro: $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al integrar codigo',data:  $registro);
        }

        $registro = $this->descripcion(registro: $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al integrar descripcion',data:  $registro);
        }
        return $registro;
    }

    public function modifica_bd(array $registro, int $id, bool $reactiva = false,
                                array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {

        $registro_previo = $this->registro(registro_id: $id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener registro_previo',data:  $registro_previo);
        }

        if(!isset($registro['descripcion'])){

            $codigo = $registro_previo['fc_pago_pago_codigo'];
            if(isset($registro['codigo'])){
                $codigo = $registro['codigo'];
            }

            $descripcion = $codigo;
            $registro['descripcion'] = $descripcion;
        }
        $r_modifica_bd  = parent::modifica_bd(registro: $registro,id:  $id,reactiva:  $reactiva,
            keys_integra_ds:  $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar',data:  $r_modifica_bd);
        }

        $registro = $this->registro(registro_id: $id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener registro',data:  $registro);
        }

        $regenera_totales = $this->regenera_totales(fc_pago_id: $registro['fc_pago_id']);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener totales',data:  $regenera_totales);
        }

        return $r_modifica_bd;
    }

    /**
     * Integra un monto basado con el tipo de cambio de operacion en pesos
     * @param string $key_monto Key a integrar
     * @param float $monto_total_mxn Monto total previo para acumular
     * @param array $row Registro en proceso
     * @return float
     */
    private function monto_mxn(string $key_monto, float $monto_total_mxn, array $row): float
    {
        $monto = round($row[$key_monto],2);
        $monto_mxn = round($monto * $row['com_tipo_cambio_monto'],2);
        $monto_total_mxn +=$monto_mxn;
        return $monto_total_mxn;
    }

    /**
     * Obtiene el monto total de pagos aplicados
     * @param int $fc_pago_id Pago Id
     * @return array|float
     *
     */
    private function monto_total_pagos_mxn(int $fc_pago_id): float|array
    {
        $filtro['fc_pago_id'] = $fc_pago_id;

        $r_fc_pagos = (new fc_pago_pago(link: $this->link))->filtro_and(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener r_fc_pagos',data:  $r_fc_pagos);
        }
        $fc_pagos = $r_fc_pagos->registros;


        $monto_mxn = $this->acumula_monto_mxn(key_monto: 'fc_pago_pago_monto', rows: $fc_pagos);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener monto_mxn',data:  $monto_mxn);
        }

        return round($monto_mxn,2);
    }

    private function total_retenciones_mxn(string $cat_sat_tipo_impuesto_codigo, int $fc_pago_id): float|array
    {
        $filtro['fc_pago.id'] = $fc_pago_id;
        $filtro['cat_sat_tipo_impuesto.codigo'] = $cat_sat_tipo_impuesto_codigo;

        $r_fc_retencion_dr_part = (new fc_retencion_dr_part(link: $this->link))->filtro_and(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener r_fc_retencion_dr_part',data:  $r_fc_retencion_dr_part);
        }

        $fc_retenciones_dr_part = $r_fc_retencion_dr_part->registros;


        $monto_mxn = $this->acumula_monto_mxn(key_monto: 'fc_retencion_dr_part_importe_dr', rows: $fc_retenciones_dr_part);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener monto_mxn',data:  $monto_mxn);
        }


        return round($monto_mxn,2);
    }

    private function traslados_dr_part(float $cat_sat_factor_factor, string $cat_sat_tipo_factor_descripcion, int $fc_pago_id){
        $filtro = $this->filtro_traslado_dr(cat_sat_factor_factor: $cat_sat_factor_factor,
            cat_sat_tipo_factor_descripcion:  $cat_sat_tipo_factor_descripcion,fc_pago_id:  $fc_pago_id);

        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener filtro',data:  $filtro);
        }

        $r_fc_traslado_dr_part = (new fc_traslado_dr_part(link: $this->link))->filtro_and(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener r_fc_traslado_dr_part',data:  $r_fc_traslado_dr_part);
        }

        return $r_fc_traslado_dr_part->registros;
    }

    private function total_traslados_base_iva_mxn(float $cat_sat_factor_factor, string $cat_sat_tipo_factor_descripcion, int $fc_pago_id): float|array
    {

        $monto_mxn = $this->monto_mxn_traslado(cat_sat_factor_factor: $cat_sat_factor_factor,
            cat_sat_tipo_factor_descripcion: $cat_sat_tipo_factor_descripcion, fc_pago_id: $fc_pago_id,
            key_monto: 'fc_traslado_dr_part_base_dr');
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener monto_mxn',data:  $monto_mxn);
        }

        return round($monto_mxn,2);
    }

    private function total_traslados_impuesto_iva_mxn(float $cat_sat_factor_factor, string $cat_sat_tipo_factor_descripcion, int $fc_pago_id): float|array
    {


        $monto_mxn = $this->monto_mxn_traslado(cat_sat_factor_factor: $cat_sat_factor_factor,
            cat_sat_tipo_factor_descripcion: $cat_sat_tipo_factor_descripcion, fc_pago_id: $fc_pago_id,
            key_monto: 'fc_traslado_dr_part_importe_dr');
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener monto_mxn',data:  $monto_mxn);
        }


        return round($monto_mxn,2);
    }

    private function monto_mxn_traslado(float $cat_sat_factor_factor, string $cat_sat_tipo_factor_descripcion, int $fc_pago_id, string $key_monto){
        $fc_traslados_dr_part = $this->traslados_dr_part(cat_sat_factor_factor: $cat_sat_factor_factor,
            cat_sat_tipo_factor_descripcion:  $cat_sat_tipo_factor_descripcion, fc_pago_id: $fc_pago_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener fc_traslados_dr_part',data:  $fc_traslados_dr_part);
        }

        $monto_mxn = $this->acumula_monto_mxn(key_monto: $key_monto, rows: $fc_traslados_dr_part);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener monto_mxn',data:  $monto_mxn);
        }

        return round($monto_mxn,2);
    }

    private function filtro_traslado_dr(float $cat_sat_factor_factor, string $cat_sat_tipo_factor_descripcion, int $fc_pago_id): array
    {
        $filtro['fc_pago.id'] = $fc_pago_id;
        $filtro['cat_sat_factor.factor'] = $cat_sat_factor_factor;
        $filtro['cat_sat_tipo_factor.descripcion'] = $cat_sat_tipo_factor_descripcion;
        return $filtro;
    }

    private function acumula_monto_mxn(string $key_monto, array $rows){
        $monto_mxn = 0.0;
        foreach ($rows as $row){
            $monto_mxn = $this->monto_mxn(key_monto: $key_monto, monto_total_mxn: $monto_mxn,row:  $row);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al obtener monto_mxn',data:  $monto_mxn);
            }
        }
        return $monto_mxn;
    }

    final public function regenera_totales(int $fc_pago_id){
        $fc_pago_totales = $this->fc_pago_totales(fc_pago_id: $fc_pago_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener totales',data:  $fc_pago_totales);
        }

        $monto_total_pagos_mxn = $this->monto_total_pagos_mxn(fc_pago_id: $fc_pago_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener totales',data:  $monto_total_pagos_mxn);
        }
        $fc_pago_total_upd['monto_total_pagos'] = $monto_total_pagos_mxn;

        $total_traslados_base_iva_16_mxn = $this->total_traslados_base_iva_mxn(cat_sat_factor_factor:0.16,
            cat_sat_tipo_factor_descripcion: 'Tasa', fc_pago_id: $fc_pago_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener totales',data:  $total_traslados_base_iva_16_mxn);
        }

        $fc_pago_total_upd['total_traslados_base_iva_16'] = $total_traslados_base_iva_16_mxn;

        $total_traslados_base_iva_08_mxn = $this->total_traslados_base_iva_mxn(cat_sat_factor_factor:0.08,
            cat_sat_tipo_factor_descripcion: 'Tasa', fc_pago_id: $fc_pago_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener totales',data:  $total_traslados_base_iva_16_mxn);
        }

        $fc_pago_total_upd['total_traslados_base_iva_08'] = $total_traslados_base_iva_08_mxn;

        $total_traslados_base_iva_00_mxn = $this->total_traslados_base_iva_mxn(cat_sat_factor_factor:0.00,
            cat_sat_tipo_factor_descripcion: 'Tasa', fc_pago_id: $fc_pago_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener totales',data:  $total_traslados_base_iva_16_mxn);
        }

        $fc_pago_total_upd['total_traslados_base_iva_00'] = $total_traslados_base_iva_00_mxn;

        $total_traslados_impuesto_iva_16_mxn = $this->total_traslados_impuesto_iva_mxn(cat_sat_factor_factor:0.16, cat_sat_tipo_factor_descripcion: 'Tasa', fc_pago_id: $fc_pago_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener totales',data:  $total_traslados_impuesto_iva_16_mxn);
        }

        $fc_pago_total_upd['total_traslados_impuesto_iva_16'] = $total_traslados_impuesto_iva_16_mxn;

        $total_traslados_impuesto_iva_08_mxn = $this->total_traslados_impuesto_iva_mxn(cat_sat_factor_factor:0.08, cat_sat_tipo_factor_descripcion: 'Tasa', fc_pago_id: $fc_pago_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener totales',data:  $total_traslados_impuesto_iva_08_mxn);
        }

        $fc_pago_total_upd['total_traslados_impuesto_iva_08'] = $total_traslados_impuesto_iva_08_mxn;

        $total_traslados_impuesto_iva_00_mxn = $this->total_traslados_impuesto_iva_mxn(cat_sat_factor_factor:0.00, cat_sat_tipo_factor_descripcion: 'Tasa', fc_pago_id: $fc_pago_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener totales',data:  $total_traslados_impuesto_iva_00_mxn);
        }

        $fc_pago_total_upd['total_traslados_impuesto_iva_00'] = $total_traslados_impuesto_iva_00_mxn;


        $total_retenciones_iva_mxn = $this->total_retenciones_mxn(cat_sat_tipo_impuesto_codigo: 'IVA',fc_pago_id:  $fc_pago_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener totales',data:  $total_retenciones_iva_mxn);
        }

        $fc_pago_total_upd['total_retenciones_iva'] = $total_retenciones_iva_mxn;

        $total_retenciones_ieps_mxn = $this->total_retenciones_mxn(cat_sat_tipo_impuesto_codigo: 'IEPS',fc_pago_id:  $fc_pago_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener totales',data:  $total_retenciones_ieps_mxn);
        }

        $fc_pago_total_upd['total_retenciones_ieps'] = $total_retenciones_ieps_mxn;

        $total_retenciones_isr_mxn = $this->total_retenciones_mxn(cat_sat_tipo_impuesto_codigo: 'ISR',fc_pago_id:  $fc_pago_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener totales',data:  $total_retenciones_isr_mxn);
        }

        $fc_pago_total_upd['total_retenciones_isr'] = $total_retenciones_isr_mxn;

        $updates = array();
        foreach ($fc_pago_totales as $fc_pago_total){
            $r_fc_pago_total = (new fc_pago_total(link: $this->link))->modifica_bd(registro:  $fc_pago_total_upd,
                id: $fc_pago_total['fc_pago_total_id']);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al actualizar totales',data:  $r_fc_pago_total);
            }
            $updates[] = $r_fc_pago_total;
        }

        return $updates;
    }



}