<?php
namespace gamboamartin\facturacion\models;
use base\orm\_modelo_parent;
use gamboamartin\cat_sat\models\cat_sat_tipo_de_comprobante;
use gamboamartin\comercial\models\com_cliente;
use gamboamartin\comercial\models\com_sucursal;
use gamboamartin\errores\errores;
use gamboamartin\organigrama\models\org_sucursal;
use PDO;
use stdClass;


class fc_uuid extends _modelo_parent {
    public function __construct(PDO $link){
        $tabla = 'fc_uuid';
        $columnas = array($tabla=>false,'org_sucursal'=>$tabla,'com_sucursal'=>$tabla,
            'cat_sat_tipo_de_comprobante'=>$tabla,'org_empresa'=>'org_sucursal','com_cliente'=>'com_sucursal',
            'dp_calle_pertenece'=>'com_sucursal','dp_colonia_postal'=>'dp_calle_pertenece','dp_cp'=>'dp_colonia_postal');
        $campos_obligatorios = array('codigo','org_sucursal_id','com_sucursal_id','cat_sat_tipo_de_comprobante_id');

        $no_duplicados = array('uuid');

        $campos_view = array();


        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, campos_view: $campos_view, columnas_extra: array(),
            no_duplicados: $no_duplicados, tipo_campos: array());

        $this->NAMESPACE = __NAMESPACE__;

        $this->etiqueta = 'UUID Externos';

    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        $cat_sat_tipo_de_comprobante = (new cat_sat_tipo_de_comprobante(link: $this->link))->registro(
            registro_id: $this->registro['cat_sat_tipo_de_comprobante_id'],retorno_obj: true);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener cat_sat_tipo_de_comprobante',data:  $cat_sat_tipo_de_comprobante);
        }
        $org_sucursal = (new org_sucursal(link: $this->link))->registro(
            registro_id: $this->registro['org_sucursal_id'],retorno_obj: true);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener org_sucursal',data:  $org_sucursal);
        }
        $com_sucursal = (new com_sucursal(link: $this->link))->registro(
            registro_id: $this->registro['com_sucursal_id'],retorno_obj: true);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener com_sucursal',data:  $com_sucursal);
        }

        if(!isset($this->registro['descripcion'])){
            $descripcion = $cat_sat_tipo_de_comprobante->cat_sat_tipo_de_comprobante_descripcion;
            $descripcion .= ' '.$org_sucursal->org_sucursal_descripcion;
            $descripcion .= ' '.$com_sucursal->com_sucursal_descripcion;
            $descripcion .= ' '.$this->registro['uuid'];
            $descripcion .= ' '.$this->registro['fecha'];
            $descripcion .= ' '.$this->registro['folio'];
            $this->registro['descripcion'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd($keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al dar de alta',data:  $r_alta_bd);
        }
        return $r_alta_bd;
    }


}