<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace gamboamartin\facturacion\controllers;

use config\generales;
use gamboamartin\errores\errores;
use gamboamartin\system\system;
use JsonException;
use PDO;
use stdClass;
use Throwable;

final class controlador_adm_session extends \gamboamartin\controllers\controlador_adm_session {
    public bool $existe_msj = false;
    public string $include_menu = '';
    public string $mensaje_html = '';

    // nuevo

    public ?string $logo_empresa_url = null;


    /////////////////////////////////////////////////////

 public function __construct(...$args)
    {
        parent::__construct(...$args);
        $this->set_logo_empresa_url_global();
    }

    /**
     * Funcion de controlador donde se ejecutaran siempre que haya un acceso denegado
     * @version 1.0.0
     * @param bool $header Si header es true cualquier error se mostrara en el html y cortara la ejecucion del sistema
     *              En false retornara un array si hay error y un string con formato html
     * @param bool $ws Si ws es true retornara el resultado en formato de json
     * @return array vacio siempre
     */
    public function denegado(bool $header, bool $ws = false): array
    {

        $this->include_menu = (new generales())->path_base;
        $this->include_menu .= 'templates/inicio.php';

        if($ws){
            $error = $this->errores->error(mensaje: 'Acceso denegado',data: array());
            header('Content-Type: application/json');
            try {
                echo json_encode($error, JSON_THROW_ON_ERROR);
            }
            catch (Throwable $e){
                echo print_r($e, true);
            }
            exit;
        }
        return array();
    }

    /**
     * Funcion de controlador donde se ejecutaran los elementos necesarios para poder mostrar el inicio en
     *      session/inicio
     * @version 1.0.0
     * @param bool $aplica_template Si aplica template buscara el header de la base
     *              No recomendado para vistas ajustadas como esta
     * @param bool $header Si header es true cualquier error se mostrara en el html y cortara la ejecucion del sistema
     *              En false retornara un array si hay error y un string con formato html
     * @param bool $ws Si ws es true retornara el resultado en formato de json
     * @return string|array string = html array = error
     * @throws JsonException si hay error en forma ws
     */
    public function inicio(bool $aplica_template = false, bool $header = true, bool $ws = false): string|array
    {

        $template =  parent::inicio($aplica_template, false); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(mensaje:  'Error al generar template',data: $template, header: $header, ws: $ws);
        }

        $this->include_menu = (new generales())->path_base;
        $this->include_menu .= 'templates/inicio.php';

        return $template;
    }

    /**
     * Funcion de controlador donde se ejecutaran los elementos necesarios para la asignacion de datos de logueo
     * @param bool $header Si header es true cualquier error se mostrara en el html y cortara la ejecucion del sistema
     *              En false retornara un array si hay error y un string con formato html
     * @param bool $ws Si ws es true retornara el resultado en formato de json
     * @param string $accion_header
     * @param string $seccion_header
     * @return array string = html array = error
     *
     */
    public function loguea(bool $header, bool $ws = false, string $accion_header = 'login', string $seccion_header = 'adm_session'): array
    {

        $loguea = parent::loguea(header: true,accion_header:  $accion_header,
            seccion_header:  $seccion_header); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(mensaje:  'Error al loguear',data: $loguea, header: $header, ws: $ws);
        }

        return $loguea;
    }


    /**
     * Funcion de controlador donde se ejecutaran los elementos de session/login
     *
     * @param bool $header Si header es true cualquier error se mostrara en el html y cortara la ejecucion del sistema
     *              En false retornara un array si hay error y un string con formato html
     * @param bool $ws Si ws es true retornara el resultado en formato de json
     * @return string|array string = html array = error
     */
    public function login(bool $header = true, bool $ws = false): stdClass|array
    {

        $login = parent::login($header, $ws); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(mensaje:  'Error al generar template',data: $login, header: $header, ws: $ws);
        }

        $this->mensaje_html = '';
        if(isset($_GET['mensaje']) && $_GET['mensaje'] !==''){
            $mensaje = trim($_GET['mensaje']);
            if($mensaje !== ''){
                $this->mensaje_html = $mensaje;
                $this->existe_msj = true;
            }
        }

        $this->include_menu .= 'templates/login.php';

        return $login;

    }
//////////////////////////////////////////////////////////////////////////////////////
    protected function set_logo_empresa_url_global(): void
    {
        $this->logo_empresa_url = null;

        try {
            $org_empresa_id = (int)($_GET['org_empresa_id'] ?? 0);

            if ($org_empresa_id <= 0) {
                $modelo_empresa = new \gamboamartin\organigrama\models\org_empresa($this->link);
                $r_emp = $modelo_empresa->filtro_and(
                    aplica_seguridad: false,
                    columnas: ['org_empresa_id'],
                    filtro: ['org_empresa.status' => 'activo'],
                    limit: 1,
                    order: ['org_empresa.id' => 'ASC']
                );
                if (\gamboamartin\errores\errores::$error) return;
                $org_empresa_id = (int)($r_emp->registros[0]['org_empresa_id'] ?? 0);
            }

            if ($org_empresa_id <= 0) return;

            $modelo_logo = new \gamboamartin\organigrama\models\org_logo($this->link);

            // 1) Traer doc_documento_id del logo principal
            $r_logo = $modelo_logo->filtro_and(
                aplica_seguridad: false,
                columnas: ['org_logo_doc_documento_id'],
                filtro: [
                    'org_logo.status' => 'activo',
                    'org_logo.es_principal' => 'activo',
                    'org_logo.org_empresa_id' => $org_empresa_id
                ],
                limit: 1,
                order: ['org_logo.id' => 'DESC']
            );
            if (\gamboamartin\errores\errores::$error) return;

            $doc_id = (int)($r_logo->registros[0]['org_logo_doc_documento_id'] ?? 0);
            if ($doc_id <= 0) return;

            // 2) Traer ruta del documento
            $modelo_doc = new \gamboamartin\documento\models\doc_documento($this->link);
            $r_doc = $modelo_doc->filtro_and(
                aplica_seguridad: false,
                columnas: ['doc_documento_ruta_relativa'],
                filtro: ['doc_documento.id' => $doc_id],
                limit: 1
            );
            if (\gamboamartin\errores\errores::$error) return;

            $ruta = (string)($r_doc->registros[0]['doc_documento_ruta_relativa'] ?? '');
            if ($ruta === '') return;

            $this->logo_empresa_url = '/facturacion/' . ltrim($ruta, '/');
        } catch (\Throwable $e) {
            $this->logo_empresa_url = null;
        }
    }

//////////////////////////////////////////////////////////////////////////////

}
