<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace gamboamartin\facturacion\controllers;

use base\controller\controler;
use gamboamartin\errores\errores;
use gamboamartin\facturacion\html\fc_conf_etapa_rel_html;
use gamboamartin\facturacion\models\fc_conf_etapa_rel;
use gamboamartin\proceso\html\pr_etapa_proceso_html;
use gamboamartin\system\_ctl_base;
use gamboamartin\system\links_menu;

use gamboamartin\template\html;
use PDO;
use stdClass;

class controlador_fc_conf_etapa_rel extends _ctl_base{


    public function __construct(PDO      $link, html $html = new \gamboamartin\template_1\html(),
                                stdClass $paths_conf = new stdClass())
    {
        $modelo = new fc_conf_etapa_rel(link: $link);
        $html_ = new fc_conf_etapa_rel_html(html: $html);
        $obj_link = new links_menu(link: $link, registro_id: $this->registro_id);

        $datatables = $this->init_datatable();
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al inicializar datatable', data: $datatables);
            print_r($error);
            die('Error');
        }

        parent::__construct(html: $html_, link: $link, modelo: $modelo, obj_link: $obj_link, datatables: $datatables,
            paths_conf: $paths_conf);

        $configuraciones = $this->init_configuraciones();
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al inicializar configuraciones', data: $configuraciones);
            print_r($error);
            die('Error');
        }


    }

    public function alta(bool $header, bool $ws = false): array|string
    {
        $r_alta = parent::alta($header, $ws); // TODO: Change the autogenerated stub
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al generar template', data: $r_alta);
            print_r($error);
            die('Error');
        }


        $pr_etapa_proceso_id = (new pr_etapa_proceso_html(html: $this->html_base))->select_pr_etapa_proceso_id(cols: 12,
            con_registros: true, id_selected: -1, link: $this->link);
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al generar input', data: $pr_etapa_proceso_id);
            print_r($error);
            die('Error');
        }

        $this->inputs = new stdClass();
        $this->inputs->pr_etapa_proceso_id = $pr_etapa_proceso_id;

        return $r_alta;

    }

    public function modifica(bool $header, bool $ws = false): array|stdClass
    {
        $r_modifica = parent::modifica($header, $ws); // TODO: Change the autogenerated stub
        if(errores::$error){
            $error = $this->errores->error(mensaje: 'Error al generar template', data: $r_modifica);
            print_r($error);
            die('Error');
        }

        $pr_etapa_proceso_id = (new pr_etapa_proceso_html(html: $this->html_base))->select_pr_etapa_proceso_id(cols: 12,
            con_registros: true, id_selected:$this->row_upd->pr_etapa_proceso_id, link: $this->link);
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al generar input', data: $pr_etapa_proceso_id);
            print_r($error);
            die('Error');
        }

        $this->inputs = new stdClass();
        $this->inputs->pr_etapa_proceso_id = $pr_etapa_proceso_id;

        return $r_modifica;
    }


    private function init_configuraciones(): controler
    {
        $this->seccion_titulo = 'Conf Etapas con relacion';
        $this->titulo_lista = 'Configuracion de etapas';

        return $this;
    }



    private function init_datatable(): stdClass
    {
        $columns["fc_conf_etapa_rel_id"]["titulo"] = "Id";
        $columns["pr_etapa_descripcion"]["titulo"] = "Etapa";

        $filtro = array("fc_conf_etapa_rel.id","pr_etapa.descripcion");

        $datatables = new stdClass();
        $datatables->columns = $columns;
        $datatables->filtro = $filtro;

        return $datatables;
    }


}
