<?php

namespace gamboamartin\facturacion\controllers;


use gamboamartin\comercial\models\com_tipo_contacto;
use gamboamartin\errores\errores;
use gamboamartin\facturacion\models\_email_validacion;
use gamboamartin\facturacion\models\fc_empleado;
use gamboamartin\facturacion\models\fc_empleado_contacto;
use gamboamartin\system\html_controler;
use gamboamartin\system\links_menu;
use gamboamartin\system\system;
use gamboamartin\template_1\html;
use PDO;
use stdClass;


class controlador_fc_empleado_contacto extends system {

    public const string STATUS_NO_VALIDADO = 'no validado';
    public const string STATUS_LINK_ENVIADO = 'link enviado';
    public const string STATUS_VALIDADO = 'validado';
    public function __construct(PDO $link, html $html = new html(), stdClass $paths_conf = new stdClass()){

        $modelo = new fc_empleado_contacto(link: $link);
        $html_ = new html_controler($html);
        $obj_link = new links_menu(link: $link, registro_id:  $this->registro_id);

        $columns["fc_empleado_nombre_completo"]["titulo"] = "Empleado";
        $columns["com_tipo_contacto_descripcion"]["titulo"] = "Tipo contacto";
        $columns["fc_empleado_contacto_descripcion"]["titulo"] = "Contacto";
        $columns["fc_empleado_contacto_telefono"]["titulo"] = "Telefono";
        $columns["fc_empleado_contacto_correo"]["titulo"] = "Correo";
        $columns["fc_empleado_contacto_estatus_correo"]["titulo"] = "Validacion Correo";

        $filtro = [
            "fc_empleado.nombre_completo",
            "com_tipo_contacto.descripcion",
            "fc_empleado_contacto.descripcion",
            "fc_empleado_contacto.telefono",
            "fc_empleado_contacto.correo",
            "fc_empleado_contacto.estatus_correo",
        ];

        $datatables = new stdClass();
        $datatables->columns = $columns;
        $datatables->filtro = $filtro;

        parent::__construct(
            html:$html_, link: $link,modelo:  $modelo, obj_link: $obj_link,
            datatables:  $datatables, paths_conf: $paths_conf
        );

    }

    public function alta(bool $header, bool $ws = false): array|string
    {
        $alta = parent::alta($header, $ws); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input', data: $alta,header:  $header,ws:  $ws);
        }

        $result_inputs = $this->generar_inputs(registro: [], value_vacio: true);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar inputs del alta',
                data: $result_inputs, header: $header, ws: $ws);

        }

        return $alta;
    }

    public function lista(bool $header, bool $ws = false): array
    {
        (new fc_empleado_contacto(link: $this->link))->valida_tiempo_tokens();
        $lista = parent::lista($header, $ws);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error en lista', data: $lista, header:  $header,ws:  $ws);
        }

        return $lista;
    }

    public function modifica(bool $header, bool $ws = false): array|stdClass
    {
        $modifica = parent::modifica($header, $ws); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input', data: $modifica, header:  $header,ws:  $ws);
        }

        $registro = $this->registro;

        $result_inputs = $this->generar_inputs(registro: $registro, value_vacio: false);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar inputs del modifica',
                data: $result_inputs, header: $header, ws: $ws);

        }

        return $modifica;
    }

    public function valida_correo(bool $header, bool $ws = false)
    {

        $data = $this->modelo->obten_data();
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al obtener data',
                data: $data, header: $header, ws: $ws);

        }

        $registro_id = $data['fc_empleado_contacto_id'];
        $correo = $data['fc_empleado_contacto_correo'];

        if ($data['fc_empleado_contacto_estatus_correo'] === self::STATUS_VALIDADO) {
            return $this->retorno_error(mensaje: 'El correo ya fue validado',
                data: $data, header: $header, ws: $ws);
        }

        $modelo_fc_empleado_contacto = new fc_empleado_contacto(link: $this->link);

        $url_validacion = $modelo_fc_empleado_contacto->genera_link_validacion($correo, $registro_id);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al obtener url validacion',
                data: $data, header: $header, ws: $ws);
        }

        $rs = $modelo_fc_empleado_contacto->actualiza_estado_correo(
            registro_id: $registro_id,
            estado: self::STATUS_LINK_ENVIADO
        );
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error en actualiza_estado_correo',
                data: $rs, header: $header, ws: $ws);
        }

        $email = new _email_validacion();
        $resultado = $email->enviar_validacion(
            correo_destino: $correo,
            url_validacion: $url_validacion,
            link: $this->link
        );
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error en enviar_validacion',
                data: $resultado, header: $header, ws: $ws);
        }

        $_SESSION['exito'][]['mensaje'] = 'link de validacion enviado exitosamente';
        $link = "index.php?seccion=fc_empleado_contacto&accion=lista&adm_menu_id=75";
        $link .= "&session_id={$_GET['session_id']}";
        header("Location: " . $link);
        exit;

    }

    private function generar_inputs(array $registro, bool $value_vacio): array
    {

        $empleado_id = -1;
        $tipo_contacto_id = -1;

        $registro_stdClass = new stdClass();

        if(!empty($registro)) {
            $empleado_id = $registro['fc_empleado_contacto_fc_empleado_id'];
            $tipo_contacto_id = $registro['fc_empleado_contacto_com_tipo_contacto_id'];
            $registro_stdClass->nombre = $registro['fc_empleado_contacto_nombre'];
            $registro_stdClass->ap = $registro['fc_empleado_contacto_ap'];
            $registro_stdClass->am = $registro['fc_empleado_contacto_am'];
            $registro_stdClass->telefono = $registro['fc_empleado_contacto_telefono'];
            $registro_stdClass->correo = $registro['fc_empleado_contacto_correo'];
        }




        $this->inputs = new stdClass();

        $modelo_fc_empleado = new fc_empleado(link: $this->link);
        $filtro_input_select_empleado = [];

        $input_select_empleado = $this->html->select_catalogo(cols: 12, con_registros: true,
            id_selected: $empleado_id,
            modelo: $modelo_fc_empleado, columns_ds: ['fc_empleado_nombre_completo', 'fc_empleado_rfc'],
            disabled: false, filtro: $filtro_input_select_empleado, label: 'Empleado',
            name: 'fc_empleado_id', registros: [], required: true
        );
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al generar $input_select_empleado', data: $input_select_empleado);
        }

        $this->inputs->empleado = $input_select_empleado;

        $modelo_com_tipo_contacto = new com_tipo_contacto(link: $this->link);
        $filtro_input_select_tipo_contacto = [];

        $input_select_tipo_contacto = $this->html->select_catalogo(cols: 12, con_registros: true,
            id_selected: $tipo_contacto_id,
            modelo: $modelo_com_tipo_contacto, columns_ds: ['com_tipo_contacto_descripcion_select'],
            disabled: false, filtro: $filtro_input_select_tipo_contacto, label: 'Tipo Contacto',
            name: 'com_tipo_contacto_id', registros: [], required: true
        );
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al generar $input_select_tipo_contacto', data: $input_select_tipo_contacto);
        }

        $this->inputs->tipo_contacto = $input_select_tipo_contacto;

        $input_nombre = $this->html->input_text_required(
            cols: 4,disabled: false, name: 'nombre', place_holder: 'Nombre',
            row_upd: $registro_stdClass, value_vacio: $value_vacio, title: 'Nombre'
        );
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al generar $input_nombre', data: $input_nombre);
        }
        $this->inputs->nombre = $input_nombre;

        $input_ap = $this->html->input_text_required(
            cols: 4,disabled: false, name: 'ap', place_holder: 'Apellido Paterno',
            row_upd: $registro_stdClass, value_vacio: $value_vacio, title: 'Apellido Paterno'
        );
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al generar $input_ap', data: $input_ap);
        }
        $this->inputs->ap = $input_ap;

        $input_am = $this->html->input_text(
            cols: 4,disabled: false, name: 'am', place_holder: 'Apellido Materno',
            row_upd: $registro_stdClass,value_vacio: $value_vacio, title: 'Apellido Materno'
        );
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al generar $input_am', data: $input_am);
        }
        $this->inputs->am = $input_am;

        $input_telefono = $this->html->input_text_required(
            cols: 6,disabled: false, name: 'telefono', place_holder: 'Telefono',
            row_upd: $registro_stdClass,value_vacio: $value_vacio, title: 'Telefono'
        );
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al generar $input_telefono', data: $input_telefono);
        }
        $this->inputs->telefono = $input_telefono;

        $input_correo = $this->html->input_text_required(
            cols: 6,disabled: false, name: 'correo', place_holder: 'Correo',
            row_upd: $registro_stdClass,value_vacio: $value_vacio, title: 'Correo'
        );
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al generar $input_correo', data: $input_correo);
        }
        $this->inputs->correo = $input_correo;

        return [];
    }
}
