<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace gamboamartin\facturacion\controllers;

use config\generales;
use gamboamartin\errores\errores;
use gamboamartin\facturacion\models\adm_usuario;
use gamboamartin\facturacion\models\com_agente;
use gamboamartin\template\html;
use PDO;
use stdClass;

class controlador_com_agente extends \gamboamartin\comercial\controllers\controlador_com_agente {

    public string $url_submit = '#';
    private array $ids_grupo_validos = [4,5];
    public int $com_tipo_agente_id;
    public int $tipo_agente_asesor_id;
    public string $numero_asesor;
    public int $info_total_agentes;
    public int $info_agentes_activos;
    public int $info_asesores;

    public bool $aplica_relacion_agentes = false;

    public function __construct(PDO $link, html $html = new \gamboamartin\template_1\html(), stdClass $paths_conf = new stdClass())
    {
        parent::__construct(link: $link,html:  $html,paths_conf:  $paths_conf);
        $this->modelo = new com_agente($link);

        $this->childrens_data['com_agente']['title'] = 'Agente';

        $config_general = new generales();
        if (isset($config_general->aplica_relacion_agentes)) {
            $this->aplica_relacion_agentes = $config_general->aplica_relacion_agentes;
        }
        $this->tipo_agente_asesor_id = $this->conf_generales::$tipo_agente_asesor;
    }

    public function alta(bool $header, bool $ws = false): array|string
    {
        $link = "index.php?seccion=com_agente&accion=alta_bd&registro_id={$this->registro_id}&session_id={$_GET['session_id']}";
        $this->url_submit = $link;
        return parent::alta($header, $ws);
    }

    public function modifica(bool $header, bool $ws = false, array $keys_selects = array()): array|stdClass
    {
        $this->modelo->registro_id = $this->registro_id;
        $data = $this->modelo->obten_data(columnas: ['com_tipo_agente_id','com_agente_num_asesor']);
        if (errores::$error) {
            return $this->retorno_error(
                mensaje: 'Error al obtener info del agente', data: $data, header: $header, ws: $ws);
        }

        $this->numero_asesor = $data['com_agente_num_asesor'] ?? '0';

        $link = "index.php?seccion=com_agente&accion=modifica_bd&registro_id={$this->registro_id}&session_id={$_GET['session_id']}";
        $this->url_submit = $link;
        return parent::modifica($header, $ws, $keys_selects); // TODO: Change the autogenerated stub
    }

    public function alta_bd(bool $header, bool $ws = false): array|stdClass
    {
        if ($this->aplica_relacion_agentes) {

            $adm_grupo_id = $this->conf_generales::$grupo_id_asesor;

            if ((int)$_POST['com_tipo_agente_id']  === $this->conf_generales::$tipo_agente_operador) {
                $adm_grupo_id = $this->conf_generales::$grupo_id_operadores;
            }

            $_POST['adm_grupo_id'] = $adm_grupo_id;

            $admin_user = (string)$_POST['user'];

            $resultado_validacion = $this->validad_admin_user(
                admin_user: $admin_user,
                header: $header,
                ws: $ws
            );

            if (errores::$error) {
                return $this->retorno_error(
                    mensaje: 'Error al validar user único', data: $resultado_validacion, header: $header, ws: $ws);
            }
        } // end if ($this->aplica_relacion_agentes) {



        $result = parent::alta_bd($header, $ws);
        if (errores::$error) {
            return $this->retorno_error(
                mensaje: 'Error al registrar al agente', data: $result, header: $header, ws: $ws);
        }

        $_SESSION['exito'][]['mensaje'] = 'agente creado exitosamente';
        $link = "index.php?seccion=com_agente&accion=lista&adm_menu_id=41";
        $link .= "&session_id={$_GET['session_id']}";
        header("Location: " . $link);
        exit;
    }




    public function lista(bool $header, bool $ws = false): array
    {
        $this->setear_info_lista($header, false);
        return parent::lista($header, $ws); // TODO: Change the autogenerated stub
    }

    public function modifica_bd(bool $header, bool $ws): array|stdClass
    {
        if ($this->aplica_relacion_agentes) {
            $adm_grupo_id = $this->conf_generales::$grupo_id_asesor;

            if ((int)$_POST['com_tipo_agente_id']  === $this->conf_generales::$tipo_agente_operador) {
                $adm_grupo_id = $this->conf_generales::$grupo_id_operadores;
            }

            $_POST['adm_grupo_id'] = $adm_grupo_id;

        } // end if ($this->aplica_relacion_agentes) {

        $result = parent::modifica_bd($header, $ws); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->retorno_error(
                mensaje: 'Error al modificar el agente', data: $result, header: $header, ws: $ws);
        }

        $_SESSION['exito'][]['mensaje'] = 'agente modificado exitosamente';
        $link = "index.php?seccion=com_agente&accion=modifica&adm_menu_id=41&registro_id={$this->registro_id}";
        $link .= "&session_id={$_GET['session_id']}";
        header("Location: " . $link);
        exit;
    }

    private function validad_admin_user(string $admin_user, bool $header, bool $ws)
    {
        $modelo_adm_usuario = new adm_usuario($this->link);

        $filtro = ['adm_usuario.user' => $admin_user];

        $result = $modelo_adm_usuario->filtro_and(filtro: $filtro);
        if (errores::$error) {
            return $this->retorno_error(
                mensaje: 'Error al buscar el user para su validacion', data: $result, header: $header, ws: $ws);
        }

        $numero_registros = (int)$result->n_registros;

        if ($numero_registros !== 0) {
            return $this->retorno_error(
                mensaje: "Error el user:{$admin_user} ya fue registrado previamente.", data: $result, header: $header, ws: $ws);
        }
        return [];
    }

    private function setear_info_lista(bool $header, bool $ws): void
    {
        $modelo_agente = new com_agente($this->link);
        $info = $modelo_agente->obtener_info_lista();
        if(errores::$error){
            $this->retorno_error(
                mensaje: 'Error obtener info lista',
                data: $info, header: $header, ws: $ws
            );
            return;
        }

        $this->info_total_agentes = $info->total_agentes;
        $this->info_agentes_activos = $info->agentes_activos;
        $this->info_asesores = $info->agentes_asesores;
    }

}
