<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace gamboamartin\facturacion\controllers;

use config\generales;
use gamboamartin\errores\errores;
use gamboamartin\facturacion\models\adm_usuario;
use gamboamartin\facturacion\models\com_agente;
use gamboamartin\template\html;
use PDO;
use stdClass;

class controlador_com_agente extends \gamboamartin\comercial\controllers\controlador_com_agente {

    public string $url_submit = '#';
    private array $ids_grupo_validos = [4,5];

    public bool $aplica_relacion_agentes = false;

    public function __construct(PDO $link, html $html = new \gamboamartin\template_1\html(), stdClass $paths_conf = new stdClass())
    {
        parent::__construct(link: $link,html:  $html,paths_conf:  $paths_conf);
        $this->modelo = new com_agente($link);

        $this->childrens_data['com_agente']['title'] = 'Agente';

        $config_general = new generales();
        if (isset($config_general->aplica_relacion_agentes)) {
            $this->aplica_relacion_agentes = $config_general->aplica_relacion_agentes;
        }
    }

    public function alta(bool $header, bool $ws = false): array|string
    {
        $link = "index.php?seccion=com_agente&accion=alta_bd&registro_id={$this->registro_id}&session_id={$_GET['session_id']}";
        $this->url_submit = $link;
        return parent::alta($header, $ws);
    }

    public function modifica(bool $header, bool $ws = false, array $keys_selects = array()): array|stdClass
    {
        $link = "index.php?seccion=com_agente&accion=modifica_bd&registro_id={$this->registro_id}&session_id={$_GET['session_id']}";
        $this->url_submit = $link;
        return parent::modifica($header, $ws, $keys_selects); // TODO: Change the autogenerated stub
    }

    public function alta_bd(bool $header, bool $ws = false): array|stdClass
    {
        if ($this->aplica_relacion_agentes) {

            if (!in_array($_POST['adm_grupo_id'], $this->ids_grupo_validos) ){

                return $this->retorno_error(
                    mensaje: 'Error estas intentando asignar un grupo de usuarios no valido', data: $_POST, header: $header, ws: $ws
                );
            } // end if (!in_array($_POST['adm_grupo_id'], $this->ids_grupo_validos) ){

            $admin_user = (string)$_POST['user'];

            $resultado_validacion = $this->validad_admin_user(
                admin_user: $admin_user,
                header: $header,
                ws: $ws
            );

            if (errores::$error) {
                return $this->retorno_error(
                    mensaje: 'Error al validar user único', data: $resultado_validacion, header: $header, ws: $ws);
            }
        } // end if ($this->aplica_relacion_agentes) {



        $result = parent::alta_bd($header, $ws);
        if (errores::$error) {
            return $this->retorno_error(
                mensaje: 'Error al registrar al agente', data: $result, header: $header, ws: $ws);
        }

        $_SESSION['exito'][]['mensaje'] = 'agente creado exitosamente';
        $link = "index.php?seccion=com_agente&accion=lista&adm_menu_id=41";
        $link .= "&session_id={$_GET['session_id']}";
        header("Location: " . $link);
        exit;
    }

    public function modifica_bd(bool $header, bool $ws): array|stdClass
    {
        if (!in_array($_POST['adm_grupo_id'], $this->ids_grupo_validos) ){

            return $this->retorno_error(
                mensaje: 'Error estas intentando asignar un grupo de usuarios no valido', data: $_POST, header: $header, ws: $ws
            );
        }

        $result = parent::modifica_bd($header, $ws); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->retorno_error(
                mensaje: 'Error al modificar el agente', data: $result, header: $header, ws: $ws);
        }

        $_SESSION['exito'][]['mensaje'] = 'agente modificado exitosamente';
        $link = "index.php?seccion=com_agente&accion=modifica&adm_menu_id=41&registro_id={$this->registro_id}";
        $link .= "&session_id={$_GET['session_id']}";
        header("Location: " . $link);
        exit;
    }

    private function validad_admin_user(string $admin_user, bool $header, bool $ws)
    {
        $modelo_adm_usuario = new adm_usuario($this->link);

        $filtro = ['adm_usuario.user' => $admin_user];

        $result = $modelo_adm_usuario->filtro_and(filtro: $filtro);
        if (errores::$error) {
            return $this->retorno_error(
                mensaje: 'Error al buscar el user para su validacion', data: $result, header: $header, ws: $ws);
        }

        $numero_registros = (int)$result->n_registros;

        if ($numero_registros !== 0) {
            return $this->retorno_error(
                mensaje: "Error el user:{$admin_user} ya fue registrado previamente.", data: $result, header: $header, ws: $ws);
        }
        return [];
    }
}
