<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace gamboamartin\facturacion\controllers;

use base\controller\controler;
use gamboamartin\errores\errores;
use gamboamartin\facturacion\html\fc_factura_html;
use gamboamartin\facturacion\html\fc_factura_relacionada_html;
use gamboamartin\facturacion\html\fc_relacion_html;
use gamboamartin\facturacion\models\fc_factura_relacionada;
use gamboamartin\system\_ctl_base;
use gamboamartin\system\links_menu;

use gamboamartin\template\html;
use PDO;
use stdClass;

class controlador_fc_factura_relacionada extends _ctl_base{


    public function __construct(PDO      $link, html $html = new \gamboamartin\template_1\html(),
                                stdClass $paths_conf = new stdClass())
    {
        $modelo = new fc_factura_relacionada(link: $link);
        $html_ = new fc_factura_relacionada_html(html: $html);
        $obj_link = new links_menu(link: $link, registro_id: $this->registro_id);

        $datatables = $this->init_datatable();
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al inicializar datatable', data: $datatables);
            print_r($error);
            die('Error');
        }

        parent::__construct(html: $html_, link: $link, modelo: $modelo, obj_link: $obj_link, datatables: $datatables,
            paths_conf: $paths_conf);

        $configuraciones = $this->init_configuraciones();
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al inicializar configuraciones', data: $configuraciones);
            print_r($error);
            die('Error');
        }


    }

    public function alta(bool $header, bool $ws = false): array|string
    {
        $r_alta = parent::alta($header, $ws); // TODO: Change the autogenerated stub
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al generar template', data: $r_alta);
            print_r($error);
            die('Error');
        }

        $columns_ds[] = 'fc_factura_folio';
        $columns_ds[] = 'cat_sat_tipo_relacion_descripcion';

        $fc_relacion_id = (new fc_relacion_html(html: $this->html_base))->select_fc_relacion_id(cols: 12,
            con_registros: true, id_selected: -1, link: $this->link, columns_ds: $columns_ds);
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al generar input', data: $fc_relacion_id);
            print_r($error);
            die('Error');
        }

        $columns_ds = array();
        $columns_ds[] = 'fc_factura_folio';
        $columns_ds[] = 'fc_factura_uuid';

        $fc_factura_id = (new fc_factura_html(html: $this->html_base))->select_fc_factura_id(cols: 12,
            con_registros: true, id_selected: -1, link: $this->link, columns_ds: $columns_ds);
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al generar input', data: $fc_factura_id);
            print_r($error);
            die('Error');
        }



        $this->inputs = new stdClass();
        $this->inputs->fc_factura_id = $fc_factura_id;
        $this->inputs->fc_relacion_id = $fc_relacion_id;


        return $r_alta;

    }


    private function init_configuraciones(): controler
    {
        $this->seccion_titulo = 'Relaciones';
        $this->titulo_lista = 'Registro de Relaciones';

        return $this;
    }



    private function init_datatable(): stdClass
    {
        $columns["fc_factura_relacionada_id"]["titulo"] = "Id";
        $columns["fc_factura_relacionada_fc_factura_id"]["titulo"] = "Id Factura Origen";
        $columns["fc_factura_folio"]["titulo"] = "Folio Relacionado";
        $columns["cat_sat_tipo_relacion_descripcion"]["titulo"] = "Tipo Relacion";

        $filtro = array("fc_factura.id","fc_factura.folio","cat_sat_tipo_relacion.descripcion");

        $datatables = new stdClass();
        $datatables->columns = $columns;
        $datatables->filtro = $filtro;

        return $datatables;
    }

    public function modifica(bool $header, bool $ws = false): array|stdClass
    {
        $r_modifica = parent::modifica($header, $ws); // TODO: Change the autogenerated stub
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al generar template', data: $r_modifica);
            print_r($error);
            die('Error');
        }



        $fc_relacion_id = (new fc_relacion_html(html: $this->html_base))->select_fc_relacion_id(cols: 12,
            con_registros: true, id_selected: $this->row_upd->fc_relacion_id, link: $this->link, disabled: true);
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al generar input', data: $fc_relacion_id);
            print_r($error);
            die('Error');
        }


        $fc_factura_id = (new fc_factura_html(html: $this->html_base))->select_fc_factura_id(cols: 12,
            con_registros: true, id_selected: $this->row_upd->fc_factura_id, link: $this->link, disabled: true);
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al generar input', data: $fc_factura_id);
            print_r($error);
            die('Error');
        }



        $this->inputs = new stdClass();
        $this->inputs->fc_factura_id = $fc_factura_id;
        $this->inputs->fc_relacion_id = $fc_relacion_id;
        return $r_modifica;

    }


}
