<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace gamboamartin\facturacion\controllers;

use gamboamartin\errores\errores;
use gamboamartin\template\html;
use PDO;
use stdClass;

class controlador_com_agente extends \gamboamartin\comercial\controllers\controlador_com_agente {

    public string $url_submit = '#';
    private array $ids_grupo_validos = [4,5];

    public function __construct(PDO $link, html $html = new \gamboamartin\template_1\html(), stdClass $paths_conf = new stdClass())
    {
        parent::__construct(link: $link,html:  $html,paths_conf:  $paths_conf);

        $this->childrens_data['com_agente']['title'] = 'Agente';
    }

    public function alta(bool $header, bool $ws = false): array|string
    {
        $link = "index.php?seccion=com_agente&accion=alta_bd&registro_id={$this->registro_id}&session_id={$_GET['session_id']}";
        $this->url_submit = $link;
        return parent::alta($header, $ws);
    }

    public function modifica(bool $header, bool $ws = false, array $keys_selects = array()): array|stdClass
    {
        $link = "index.php?seccion=com_agente&accion=modifica_bd&registro_id={$this->registro_id}&session_id={$_GET['session_id']}";
        $this->url_submit = $link;
        return parent::modifica($header, $ws, $keys_selects); // TODO: Change the autogenerated stub
    }

    public function alta_bd(bool $header, bool $ws = false): array|stdClass
    {

        if (!in_array($_POST['adm_grupo_id'], $this->ids_grupo_validos) ){

            return $this->retorno_error(
                mensaje: 'Error estas intentando asignar un grupo de usuarios no valido', data: $_POST, header: $header, ws: $ws
            );
        }

        $result = parent::alta_bd($header, $ws);
        if (errores::$error) {
            return $this->retorno_error(
                mensaje: 'Error al registrar al agente', data: $result, header: $header, ws: $ws);
        }

        $_SESSION['exito'][]['mensaje'] = 'agente creado exitosamente';
        $link = "index.php?seccion=com_agente&accion=lista&adm_menu_id=41";
        $link .= "&session_id={$_GET['session_id']}";
        header("Location: " . $link);
        exit;
    }

    public function modifica_bd(bool $header, bool $ws): array|stdClass
    {
        if (!in_array($_POST['adm_grupo_id'], $this->ids_grupo_validos) ){

            return $this->retorno_error(
                mensaje: 'Error estas intentando asignar un grupo de usuarios no valido', data: $_POST, header: $header, ws: $ws
            );
        }

        $result = parent::modifica_bd($header, $ws); // TODO: Change the autogenerated stub
        if (errores::$error) {
            return $this->retorno_error(
                mensaje: 'Error al modificar el agente', data: $result, header: $header, ws: $ws);
        }

        $_SESSION['exito'][]['mensaje'] = 'agente modificado exitosamente';
        $link = "index.php?seccion=com_agente&accion=modifica&adm_menu_id=41&registro_id={$this->registro_id}";
        $link .= "&session_id={$_GET['session_id']}";
        header("Location: " . $link);
        exit;
    }
}
